### ISSUE TITLE
Calling a gulpfile with gulp-hub that contains a call to gulp-hub fails

### ISSUE THREAD

**Issue by robatron** [frankwallis/gulp-hub#14]
If we call a gulpfile with gulp-hub that contained a gulp-hub call with a globstar pattern, we get the following error:

```
Error: Cannot find module 'gulp-load-plugins'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\code\rei.com\online\online-web\febs\node_modules\s
hould\gulpfile.js:2:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

However, if the child gulpfile with the gulp-hub call does not use a glob pattern, the error does not occur.

**Comment by frankwallis** [comment]
Hi, I have improved the support for recursively calling gulp-hub and added an example (see project/project1). I think your error was due to it resolving files using process.cwd() rather than relative to the actual location of the gulpfile, so I have addressed that.

please give it a try, thanks.

**Comment by frankwallis** [comment]
closing
