### ISSUE TITLE
gulp 4.0 -  throw new TypeError('`name` must be a string.');

### ISSUE THREAD

**Issue by puranjayjain** [frankwallis/gulp-hub#33]
I am running node 6.2.2 and gulp4

I tried to split my tasks across multiple files using https://github.com/gulpjs/gulp/blob/4.0/docs/recipes/split-tasks-across-multiple-files.md

but am getting this error:

```
node_modules\gulp-hub\lib\add-subtask.js:74
        throw new TypeError('`name` must be a string.');
        ^

TypeError: `name` must be a string.
    at module.exports (node_modules\gulp-hub\lib\add-subtask.js:74:15)
    at addLocalGulpTasks (node_modules\gulp-hub\lib\load-subfile.js:80:17)
    at module.exports (node_modules\gulp-hub\lib\load-subfile.js:46:13)
    at node_modules\gulp-hub\lib\index.js:42:9
    at Array.forEach (native)
    at loadFiles (node_modules\gulp-hub\lib\index.js:40:14)
    at new hub (node_modules\gulp-hub\lib\index.js:64:5)
    at Object.<anonymous> (gulpfile.js:17:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by frankwallis** [comment]
If you are using gulp4 then you need to install gulp-hub from the 4.0 branch

```
    'gulp-hub': 'frankwallis/gulp-hub#4.0'
```
